# Generated by Django 2.1.2 on 2020-03-31 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberName', models.CharField(editable=False, max_length=100)),
                ('dob', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'homeinfo',
            },
        ),
    ]
