# Generated by Django 2.1.2 on 2020-04-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeinfo', '0002_auto_20200331_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infoName', models.CharField(max_length=100)),
                ('infoValue', models.CharField(max_length=100)),
                ('updatedDate', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'placeinfo',
            },
        ),
        migrations.AlterField(
            model_name='homeinfo',
            name='memberName',
            field=models.CharField(max_length=100),
        ),
    ]
