# Generated by Django 2.1.2 on 2020-08-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UtilityInfo',
            fields=[
                ('id', models.CharField(default='19a271ebe2b8408e96e2fd8457e50a51', editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('service_company', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'db_table': 'utility_info',
            },
        ),
        migrations.CreateModel(
            name='UtilityPayments',
            fields=[
                ('id', models.CharField(default='5f40cccac981426da64f3041de3c04e9', editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(max_length=15)),
                ('service_start_date', models.DateTimeField(blank=True, null=True)),
                ('service_end_date', models.DateTimeField(blank=True, null=True)),
                ('amount', models.FloatField()),
                ('utility_id', models.ForeignKey(on_delete=False, related_name='utility_detail', to='homeutils.UtilityInfo')),
            ],
            options={
                'db_table': 'utility_payments',
            },
        ),
    ]
